### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by dbu** [shulard/http-plug-curl-adapter#1]
great job!

i looked over the code and will note feedback here. one idea would be that we create the repository in the php-http organisation and you would do a pull request - then we could comment on actual code details and github would track which comments are obsolete...
- naming: this is a httplug-react-adapter, right? it wraps the react client with the httplug interface...
- what about creating your own message factory that wraps the php-http factory and provides a method for https://github.com/shulard/httplug-react-client/blob/182adec19cffe66dde08d05d0502fcd26981a506/src/ReactHttpClient.php#L103-L109 ? its not a huge thing, but would make things unit testable.
- should a react factory instance be injected or is this the react way of doing things? https://github.com/shulard/httplug-react-client/blob/182adec19cffe66dde08d05d0502fcd26981a506/src/ReactHttpClient.php#L57
- is running the loop job of the adapter? https://github.com/shulard/httplug-react-client/blob/182adec19cffe66dde08d05d0502fcd26981a506/src/ReactHttpClient.php#L126

**Comment by shulard** [comment]
Thanks for your feedback :)

The naming is strange here because I started as an adapter and change it as a client... I think the only right name is the final one under php-http organisation :smiley:.

I tried to adapt the behaviour of React HttpClient but it seems that I get some weird behaviour with the loop. The loop is the only thing which make me move to a `Client` logic. For that I directly build the `HttpClient` instance using the Loop + DNS resolver.

I think that running the loop is not the job of this tool but no request is triggered without running the loop... Maybe we can change logic to run the loop only in sync mode ... ? For sure the loop integration logic is just interesting in sync mode and the others thing will work fine with an external loop call.

I agree with the MessageFactory logic to allow unit tests on it, I'll create it.

I'll refactor all of this stuff than I'll commit in the new repo.

Also I'll delete this repo when the migration in the new one will be finished.

**Comment by dbu** [comment]
> I tried to adapt the behaviour of React HttpClient but it seems that I
> get some weird behaviour with the loop. The loop is the only thing which
> make me move to a |Client| logic. For that I directly build the
> |HttpClient| instance using the Loop + DNS resolver.

but you still build on the react client. from my perspective, this
qualifies this package as an adapter.
btw, why not allowing to inject the client as an optional argument? then
you would use the react factory only of no react client was given. and
people obviously need to use the same loop they give you or things will
go weird.

> I think that running the loop is not the job of this tool but no request
> is triggered without running the loop... Maybe we can change logic to
> run the loop only in sync mode ... ? For sure the loop integration logic
> is just interesting in sync mode and the others thing will work fine
> with an external loop call.

i am not very familiar with reactphp (beyond the basic idea) so that was
just a wild guess. doing it in sync only seems like a good idea. but
can't there be other things in the loop that would need us to call loop
repeatedly? or could wait() call loop until the response is resolved?

**Comment by shulard** [comment]
Of course you are right :smile: this is an adapter...

I think that allowing to give a `Client` as an optional argument is a nice thing, then I'll create a HttpClientFactory to deal with the different cases :
- Build from nothing
- Build from a loop only
- Build from a loop and a DNS address / resolver

This factory will be used as a default behaviour when no parameter is given. It can also be used by the user to build an instance because it'll simplify React manipulation. The loop is still required in all the cases (but only in sync mode). I think to work synchronously, we need to build a specific loop for our adapter as a default (to avoid other stuff in the loop to be ran...).
I'll try to fix that and we can discuss on it with the updated code.

Thanks a lot for your detailed feedback :+1:

**Comment by shulard** [comment]
I've refactored objects and pushed in the new repo. If you have any others questions, I think the discussion must be moved in the new repo.
